# Generated by Django 3.2.12 on 2023-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='teacher_img')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
