# Generated by Django 3.2.12 on 2023-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_teachers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='teacher_img')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Student',
        ),
    ]
